[package]
name = "RGen"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["tokio", "canvas", "image"] }
iced_aw = { version = "0.13.0", features = ["full"] }
