[package]
name = "RGen"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10", features = ["canvas", "image", "tokio"] }
image = "0.25"
rfd = "0.15.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
